#!/bin/sh
export CATALINA_HOME="{{ tomcat_home }}"

export CATALINA_BASE="{{ tomcat_home }}"

export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/jre"

CONTENT_ROOT=-Dtds.content.root.path="{{ thredds_content_dir }}"

# set java prefs related variables (used by the wms service, for example)
JAVA_PREFS_ROOTS="-Djava.util.prefs.systemRoot=$CATALINA_HOME/content/thredds/javaUtilPrefs \
                  -Djava.util.prefs.userRoot=$CATALINA_HOME/content/thredds/javaUtilPrefs"


NORMAL="-d64 -Xmx4096m -Xms512m -server -ea"
HEAP_DUMP="-XX:+HeapDumpOnOutOfMemoryError"
HEADLESS="-Djava.awt.headless=true"

JAVA_OPTS="$CONTENT_ROOT $NORMAL $MAX_PERM_GEN $HEAP_DUMP $HEADLESS $JAVA_PREFS_ROOTS"

export JAVA_OPTS
