---
#condarecipes\tasks\main.yml
- include: setup_centos.yml
  when: setup_centos is defined and setup_centos

- include: setup_ubuntu.yml
  when: setup_ubuntu is defined and setup_ubuntu

- include: setup_conda.yml

- include: build_recipes.yml
  when: build_recipes is defined