---
- hosts: centos
  roles:
    - centos

- hosts: web-centos
  roles:
    - web-centos

- hosts: python
  roles:
    - python
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: processing

- hosts: web
  roles:
    - web
