---
- hosts: develop
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - openwind
    - nansencloud
    - doppler
    - liclipse
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: course
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts:
    - condarecipes
    - cos_condarecipes
  gather_facts: False
  roles:
    - localvm
    - conda
    - condarecipes
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: processing
  roles:
    - conda
    - nansat
    - openwind
    - nansencloud

- hosts: webserver
  roles:
    - conda
    - nansat
    - openwind
    - nansencloud
    - webserver

- hosts: thredds
  roles:
    - localvm
    - thredds

- hosts: pyoai
  roles:
    - pyoai

- hosts: travis
  roles:
    - conda
    - nansat
    - course
    - openwind
    - nansencloud
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
