---
- name: Setup DB | Run makemigrations on Nansen-Cloud project
  shell: '$HOME/miniconda/bin/python $HOME/nansen-cloud/project/manage.py makemigrations'
  tags:
    - update-nansencloud
  when: make_migrations is defined and make_migrations

- name: Setup DB | Run migrate on Nansen-Cloud project
  django_manage: >
      command=migrate
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
      settings='project.settings'
      pythonpath='{{ dev_sources_dir }}/nansen-cloud/project'
  tags:
    - update-nansencloud
  when: run_migrate is defined and run_migrate

- name: Setup DB | Update vocabularies
  django_manage: >
      command='update_vocabularies'
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
  when: run_migrate is defined and run_migrate
