---
#nansencloud\tasks\setup_python.yml

- name: Setup Python | Create condarc
  file: "path={{ home_dir }}/.condarc state=touch"

- name: Setup Python | Fix certifi breaking things
  lineinfile: "dest={{ home_dir }}/.condarc line='ssl_verify: false'"

- name: Setup Python | Install Django
  shell: 'conda install -q --yes --copy {{ item }}'
  with_items:
    django

- name: Setup Python | Install Nansencloud requirements
  shell: 'conda install -q --yes --copy -c conda-forge {{ item }}'
  with_items:
    scikit-learn
    coverage
    psycopg2
    sqlite

- name: Setup Python | Install nansen-cloud requirements
  pip: name={{ item }}
  with_items:
    - django-forms-bootstrap
    - django-leaflet
    - ipdb

- name: Setup Python | Update/checkout Nansen-Cloud Django
  git: repo=https://github.com/nansencenter/nansen-cloud
       dest="{{ dev_sources_dir }}/nansen-cloud"
       version="{{ nansencloud_version }}"
       update=yes
       force="{{ git_force_nansencloud }}"
  tags:
    - update-nansencloud

- name: Setup Python | Create link from Python dist-packages to nansen-cloud
  file: path='{{ python_dist_packages }}/nansencloud'
        src='{{ dev_sources_dir }}/nansen-cloud/nansencloud'
        state=link
        force=yes

- name: Setup Python | Create link from home directory to nansen-cloud
  file: path="{{ home_dir }}/nansen-cloud"
        src='{{ dev_sources_dir }}/nansen-cloud'
        state=link
        force=yes
  when: create_home_dir_link is defined and create_home_dir_link

#Override settings.py for non-local-db
- name: Setup Python | Override the settings.py file
  template: src=settings.py
            dest={{ project_path }}/project/settings.py
            backup=yes
  tags:
    - update-nansencloud
  when: use_local_database is not defined or not use_local_database

